### ISSUE TITLE
Doesn't really look like a proper python module

### ISSUE THREAD

**Issue by Julien00859** [Astremy/Piscord#6]
Hello :)

I've been reading the documentation of the module and I was surprise how little it is a standard-looking module.

### No tests

Not writing unittest is *very bad* and is a reason enough I wouldn't recommend anyone from using your package. Tests should be written from the ground start, all modules should roll-in their own unittests.

### Naming convention.

Citing PEP8

> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

Your modules definitely look like an old py2 module (remember Tkinter with capital T ?).

### TABS.

Citing PEP8

> Spaces are the preferred indentation method.

### Documentation

It feels like you decided to roll-in your own hand-made HTML documentation. I don't think it's a good idea. When the documentation is not strictly synced with your code, there is a *high* chance the documentation becomes outdated. The best documentation is mostly auto-generated from the code docstrings and automatically rebuild on every PR.

Take a look at [Sphinx](https://www.sphinx-doc.org/en/master/), it is the standard tool every major python project uses to document their stuff. The entire official Python documentation is generated using sphinx.

**Comment by Julien00859** [comment]
This package is garage stuff, perfectly fine if you decide to just it on your own or for projects you'll be the only maintainer.

This is not the case of this project, you want to distribute it so python newcomers can use a simple library to play with discord. As you want to distribute it, you *must* apply the same guidelines as enterprise-grade libraries.

Todo list:

- [x] PEP8
- [x] Unittest
- [x] Sphinx Documentation
- [x] Split master/dev branches
- [ ] Continuous integration

**Comment by Astremy** [comment]
Following your proposals, we have solved the main problems of piscord, I hope that this will allow us to better appreciate it.
Thanks for the recommendations, most of them are corrected now.
